changelog:
  categories:
    - title: "✨ Features"
      labels:
        - "feature"
        - "feat"
    - title: "🐛 Fixes"
      labels:
        - "bug"
        - "fix"
    - title: "♻️ Refactors"
      labels:
        - "refactor"
    - title: "🧰 CI & Build"
      labels:
        - "ci"
        - "build"
        - "chore"
    - title: "📚 Docs"
      labels:
        - "docs"
    - title: "🧪 Tests"
      labels:
        - "test"
  exclude:
    labels:
      - "skip-changelog"
