name: Install dependencies

inputs:
  install_path:
    required: true
    type: string

runs:
  using: composite
  steps:
  - name: 'Install Homebrew dependencies'
    shell: bash
    run: |
      brew install cmake ninja pkgconf qt poppler libxml2 libzip lua portaudio libsndfile qpdf zstd gettext
  - name: 'Setup ENV for future steps'
    shell: bash
    run: |
      BREW_PREFIX="$(brew --prefix)"
      QT_PREFIX="$(brew --prefix qt)"
      echo "$QT_PREFIX/bin:$BREW_PREFIX/bin:$(cat "$GITHUB_PATH")" > "$GITHUB_PATH"
      echo "PKG_CONFIG_PATH=$BREW_PREFIX/lib/pkgconfig:$QT_PREFIX/lib/pkgconfig:$BREW_PREFIX/share/pkgconfig" >> "$GITHUB_ENV"
      echo "CMAKE_PREFIX_PATH=$QT_PREFIX:$BREW_PREFIX" >> "$GITHUB_ENV"
      echo "PREFIX=$BREW_PREFIX" >> "$GITHUB_ENV"
